### ISSUE TITLE
Configure google maps keys and implemented in clinic details page.

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#50]
We should put the clinic on the map, in clinic details page.
Based on the Country, City and clinic address we should determine the LAT / LONG and.

We have the API KEY In github secrets in `GOOGLE_MAPS_API_KEY`

Related with #17 

**UPDATE**
- we should show the map using google API, because we need street view and this is not possible without the API. 
-  street view option on the map

**Comment by mariusghitoiu** [comment]
@wasile see the update in the ticket description.

**Comment by mariusghitoiu** [comment]
@wasile we have all necessary settings for the API key but it doesn't load the map. It looks like the API key is not passed to the request. See the attached screenshot. 

<img width="1877" alt="Screen Shot 2020-10-02 at 2 56 59 PM" src="https://user-images.githubusercontent.com/147089/94920743-89accd00-04bf-11eb-97d3-eb26b27d18f0.png">

**Comment by mariusghitoiu** [comment]
Fixed the issue with the key, but the pin is not correctly placed.

**Comment by andreipetcu** [comment]
This works fine with an API key with Geocoding API, Geolocation API, and Maps Javascript API enabled. 
But by the looks of Google Console API requests the Geolocation API is not used.

**Comment by andreipetcu** [comment]
It seems that the Geocoding API is not enabled.
```javascript
var myLatlng = new google.maps.LatLng(0, 0);
```
view-source:https://impreunapentrusanatate.ro/ro/clinics/goldenes-kreuz

**Comment by andreipetcu** [comment]
Applied a fix on `issues/50_maps_fix` branch.

We currently need 2 APIs enabled:

1. Maps JavaScript API for rendering the map
2. Geocoding API for determining coordinates based on address

While the Maps JS API can be restricted to a referrer since it's used in Frontend, Geocoding API cannot. Tried adding a referrer to the backend called and still got rejected.

Proposed solution is to have 1 key for the Maps JS API which will be restricted by referrer, and another for the Geocoding API which will be restricted by the server's IP Address.


GOOGLE_MAPS_JS_API_KEY=
GOOGLE_MAPS_API_KEY=

Make sure to update the ENV with these keys and appropriate values.

**Comment by andreipetcu** [comment]
Referrers could be set to 
- impreunapentrusanatate.ro/*
- dev.impreunapentrusanatate.ro/*

**Comment by andreipetcu** [comment]
<img width="592" alt="Screenshot 2020-10-22 at 22 24 16" src="https://user-images.githubusercontent.com/1076268/96920159-79cc4b80-14b5-11eb-95c4-9a22128945fa.png">
<img width="616" alt="Screenshot 2020-10-22 at 22 23 52" src="https://user-images.githubusercontent.com/1076268/96920173-7cc73c00-14b5-11eb-93a4-67856e0afc38.png">

**Comment by andreipetcu** [comment]
Generate only one key, restrict it by referrer as described above and for only those two apis. Add the key to env in `GOOGLE_MAPS_API_KEY`

**Comment by mariusghitoiu** [comment]
Looks good.
